title: Indianapolis Web Developer
email: info@davidauble.info
description: >- # this means to ignore newlines until "baseurl:"
  Indianapolis-based marketing professional with experience in working with enterprise companies, solving complex problems and visualizing big data.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://davidauble.info" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  dauble

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
livereload: true
collections:
  posts:
    output: true
sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude: [node_modules, gulpfile.js]
